name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - 'shiny_app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System libs
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libjpeg-dev \
            libx11-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: shiny_app
          packages: |
            rsconnect
            shiny
            shinydashboard
            leaflet
            plotly
            DT
            dplyr
            ggplot2
            geosphere
            readr
            jsonlite
            tidyr
            vroom
            tzdb
            cpp11
            progress

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          Rscript -e "options(repos=c(CRAN='https://cloud.r-project.org'))"
          Rscript -e "install.packages('rsconnect', repos='https://cloud.r-project.org')"
          Rscript -e "rsconnect::setAccountInfo(name=Sys.getenv('SHINYAPPS_ACCOUNT'), token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
          Rscript -e "rsconnect::deployApp(appDir='.', appName=Sys.getenv('SHINYAPPS_APPNAME'), forceUpdate=TRUE)"
