name: Deploy Shiny to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - 'shiny_app/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: false

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shiny
            any::shinydashboard
            any::leaflet
            any::plotly
            any::DT
            any::dplyr
            any::ggplot2
            any::geosphere
            any::readr
            any::jsonlite
            any::tidyr
            any::vroom
            any::tzdb
            any::cpp11
            any::progress
            any::renv
            any::rsconnect
          needs: deployment

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          rm -f renv.lock
          rm -rf renv packrat
          R -q -e "options(repos = c(CRAN = 'https://cloud.r-project.org'));
                  Sys.unsetenv('RSPM');
                  Sys.unsetenv('RENV_CONFIG_REPOS_OVERRIDE');
                  library(rsconnect);
                  rsconnect::setAccountInfo(
                    name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
                    token  = Sys.getenv('SHINYAPPS_TOKEN'),
                    secret = Sys.getenv('SHINYAPPS_SECRET'),
                    server = 'shinyapps.io'
                  );
                  rsconnect::deployApp(
                    appDir       = '.',
                    appName      = Sys.getenv('SHINYAPPS_APPNAME'),
                    envManagement= 'none',
                    forceUpdate  = TRUE
                  )"