name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - 'shiny_app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System libs
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libpng-dev \
            libjpeg-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: false

      - name: Reset renv state
        run: |
          rm -f renv.lock
          rm -rf renv

      - name: Write .Rprofile
        run: echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > .Rprofile

      - name: Init renv and install deps into project library
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://cloud.r-project.org
        run: |
          Rscript -e "options(repos=c(CRAN='https://cloud.r-project.org'));
                      if (!requireNamespace('renv', quietly=TRUE)) install.packages('renv', repos='https://cloud.r-project.org');
                      renv::init(bare=TRUE)"
          Rscript -e "renv::install(c(
                        'rsconnect',
                        'shiny','shinydashboard','leaflet','plotly','DT',
                        'dplyr','ggplot2','geosphere','readr','jsonlite',
                        'tidyr','vroom','tzdb','cpp11','progress'
                      ))"
          Rscript -e "renv::snapshot(prompt=FALSE)"
          # 檢查 lockfile 的 Repositories 區塊（應該是 cloud.r-project.org）
          sed -n '/\"Repositories\"/,+6p' renv.lock || true

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::setAccountInfo(
                        name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
                        token  = Sys.getenv('SHINYAPPS_TOKEN'),
                        secret = Sys.getenv('SHINYAPPS_SECRET')
                      );
                      rsconnect::deployApp(
                        appDir      = '.',
                        appName     = Sys.getenv('SHINYAPPS_APPNAME'),
                        forceUpdate = TRUE
                      )"
