name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches: [main]
    paths:
      - 'shiny_app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: false

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rsconnect
            any::shiny
            any::dplyr
            any::ggplot2
            any::geosphere
            any::plotly
            any::leaflet
            any::shinydashboard
            any::readr
            any::tidyr
            any::jsonlite
            any::vroom
            any::tzdb
            any::cpp11
            any::progress

      - name: Create .Rprofile for CRAN repo
        run: echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > .Rprofile

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::setAccountInfo(
                        name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
                        token  = Sys.getenv('SHINYAPPS_TOKEN'),
                        secret = Sys.getenv('SHINYAPPS_SECRET')
                      );
                      rsconnect::deployApp(
                        appDir        = '.',
                        appName       = Sys.getenv('SHINYAPPS_APPNAME'),
                        envManagement = 'none',
                        forceUpdate   = TRUE
                      )"
