name: Deploy Shiny to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - 'shiny_app/**'  # 只有改到 app 時才自動部署
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rsconnect and deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          cat > deploy.R <<'RS'
          if (!requireNamespace("rsconnect", quietly = TRUE)) {
            install.packages("rsconnect", repos = "https://cloud.r-project.org")
          }
          library(rsconnect)
          account <- Sys.getenv("SHINYAPPS_ACCOUNT")
          token   <- Sys.getenv("SHINYAPPS_TOKEN")
          secret  <- Sys.getenv("SHINYAPPS_SECRET")
          appname <- Sys.getenv("SHINYAPPS_APPNAME")
          stopifnot(nzchar(account), nzchar(token), nzchar(secret), nzchar(appname))
          rsconnect::setAccountInfo(name = account, token = token, secret = secret)
          rsconnect::deployApp(appDir = ".", appName = appname, forceUpdate = TRUE)
          RS
          Rscript deploy.R
