name: Deploy Shiny to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - 'shiny_app/**'        
      # - 'api.csv'            
      # - 'data/**'
  workflow_dispatch:            # 允許手動執行

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shiny_app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system libraries (curl/openssl/xml2)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # 取用二進位套件，較穩、較快

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # 安裝 Shiny App 需要的 R 套件（含依賴）
      - name: Install R deps for the Shiny app
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shiny
            any::shinydashboard
            any::leaflet
            any::plotly
            any::DT
            any::dplyr
            any::ggplot2
            any::geosphere
            any::readr
            any::jsonlite
            any::tidyr
            any::vroom
            any::tzdb
            any::cpp11
            any::progress
            any::renv
            any::rsconnect
          needs: deployment

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
            R -q -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); \
                     Sys.unsetenv('RSPM'); \
                     Sys.unsetenv('RENV_CONFIG_REPOS_OVERRIDE'); \
                     library(rsconnect); \
                     rsconnect::setAccountInfo( \
                       name   = Sys.getenv('SHINYAPPS_ACCOUNT'), \
                       token  = Sys.getenv('SHINYAPPS_TOKEN'), \
                       secret = Sys.getenv('SHINYAPPS_SECRET'), \
                       server = 'shinyapps.io' \
                     ); \
                     rsconnect::writeManifest(appDir='.', force=TRUE); \
                     rsconnect::deployApp( \
                       appDir='.', \
                       appName=Sys.getenv('SHINYAPPS_APPNAME'), \
                       forceUpdate=TRUE \
                     )"
